# Generated by Django 4.2.7 on 2025-09-28 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='股票代码')),
                ('name', models.CharField(max_length=100, verbose_name='股票名称')),
                ('market', models.CharField(default='SH', max_length=10, verbose_name='市场')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='所属行业')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '股票信息',
                'verbose_name_plural': '股票信息',
                'db_table': 'stock_info',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockRealtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前价格')),
                ('change_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='涨跌幅(%)')),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='涨跌金额')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='成交额')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='今日最高')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='今日最低')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='今日开盘')),
                ('pre_close', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='昨日收盘')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtime', to='stock_app.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '实时行情',
                'verbose_name_plural': '实时行情',
                'db_table': 'stock_realtime',
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='开盘价')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高价')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低价')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收盘价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='成交额')),
                ('change_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='涨跌幅(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stock_app.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '股票价格',
                'verbose_name_plural': '股票价格',
                'db_table': 'stock_price',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
